[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dental-voice-agent"
version = "0.1.0"
description = "Dental EOB Voice Agent"

[tool.pip]
no-dependencies = true